language: python
python:
  - "3.5"
# command to install dependencies
install:
  - "pip install --upgrade setuptools"
  - "pip install -r requirements.txt"
  - "pip install ."
# command to run tests
script:
  - pygcgen
  - coverage run --source pygcgen run-a-test-generation.py
  - codeclimate-test-reporter
