language: python
python:
  - "2.7"
  - "3.5"
  - "pypy"
  - "pypy3"
# command to install dependencies
install:
  - "pip install --upgrade setuptools"
  - "pip install -r requirements.txt"
  - "pip install ."
# command to run tests
script: pygcgen
